Development
StasPetrovSky1988/ChatsAPISymfony pull request #1
Opened 2022-09-28 05:19 UTC by StasPetrovSky1988

In this commit, I finished a feature where the user can create a chat.

2022-09-28 08:54 UTC, mitalcoi requested changes

2022-09-28 08:54 UTC, mitalcoi commented on src/Controller/ChatController.php
> +    public function getMessages(#[CurrentUser] ?User $user, int $idChat, ChatRepository $chatRepository): JsonResponse
зависимости уровня севрисов - вроде ChatRepository - лучше через __construct внедрять

2022-09-28 08:54 UTC, mitalcoi commented on src/Controller/ChatController.php
> +        foreach ($currentChat->getMessages() as $message) {
тут прям много логики сериализации
нормализации. может как-то можно улучшить?  Посмтри в сторону Symfony Normalizer/Serializer

2022-09-28 08:54 UTC, mitalcoi commented on src/Controller/ChatController.php
> +        $chat->addUser($user);
тут я бы избегал анемичных констуркторов, Чат очень важная сущность, и логика его создания должна быть инкапуслирована в именованом конструткоре. Что-то вроде Chat::createNewFromUserIntent($user)

2022-09-28 08:54 UTC, mitalcoi commented on src/DataFixtures/UserFixtures.php
> +        $userAdmin = User::forFixtures('Admin User', 'admin@domen.com', [User::ROLE_ADMIN, User::ROLE_USER]);
я бы избегал forFixtures. Я знаю,в коде проекта что я тебе сбрасывал так и делется, но это плохая идея. Используй готовые бизнесовые именованные конструкторы, или вообще рефлексию чтобы установить своства объекта в нужное нам состояние

2022-09-28 08:54 UTC, mitalcoi commented on src/DataFixtures/UserFixtures.php
> +        $message = Message::newMessage($userAdmin, $chat1, "This is first message by User Admin");
Давай сделаем так чтобы Message создавал наш рут аггрегат - Chat. 

Что-то вроде $chat->addNewMessage($user, $body);

2022-09-28 08:54 UTC, mitalcoi commented on src/Entity/Message.php
> +    public function setCreatedAt(\DateTimeImmutable $createdAt): self
надо стараться избегать анемичных сеттеров (да и геттеров, по правде говоря) - я понима, симфони по умолчанию генерирует именно так, но это не гуд. Сеттеров должно быть как можно меньше, в идеале их ВООБЩЕ быть не должно

2022-09-28 08:54 UTC, mitalcoi commented on src/Entity/User.php
>          if (!$this->getCreatedAt()) {
зачем этот if?

2022-09-28 08:54 UTC, mitalcoi commented on src/EventListener/JSONExceptionListener.php
> +    public function onKernelException(ExceptionEvent $event)
Гуд

2022-09-28 08:54 UTC, mitalcoi commented on src/Controller/ChatController.php
> +        foreach ($currentChat->getMessages() as $message) {
И ты не используешь DTO - напрямую сериализуешь объекты, так делать очень не рекомендуется

2022-09-28 08:54 UTC, mitalcoi commented on src/Repository/ChatRepository.php
> +    public function remove(Chat $entity, bool $flush = false): void
с flush тоже путаница небольшая, я лично не очень люблю когда в репозиториях есть флашы как таковые, флаш - это что-то на уровне приложение, оно должно быть одно и в самом конце любого flow 
Старайся использовать репозитории для ЧТЕНИЯ не для мутации

2022-09-28 12:53 UTC, kubk commented on src/Entity/Chat.php
> +        if (!$user instanceof User) throw new \LogicException("User not found");
Это недостижимый код,if никогда не выполнится

2022-09-28 12:54 UTC, kubk commented
Папку .idea лучше сразу исключить из гита (с помощью .gitignore)

Её содержимое у разработчиков разное

2022-09-29 05:38 UTC, StasPetrovSky1988 commented on src/Controller/ChatController.php
> +    public function getMessages(#[CurrentUser] ?User $user, int $idChat, ChatRepository $chatRepository): JsonResponse
Есть

2022-09-29 05:38 UTC, StasPetrovSky1988 commented on src/Controller/ChatController.php
> +        foreach ($currentChat->getMessages() as $message) {
Есть

2022-09-29 05:39 UTC, StasPetrovSky1988 commented on src/Controller/ChatController.php
> +        $chat->addUser($user);
Есть

2022-09-29 09:28 UTC, StasPetrovSky1988 commented on src/DataFixtures/UserFixtures.php
> +        $userAdmin = User::forFixtures('Admin User', 'admin@domen.com', [User::ROLE_ADMIN, User::ROLE_USER]);
Есть

2022-09-29 09:29 UTC, StasPetrovSky1988 commented on src/Entity/Message.php
> +    public function setCreatedAt(\DateTimeImmutable $createdAt): self
Есть

2022-09-29 09:42 UTC, StasPetrovSky1988 commented on src/Entity/User.php
>          if (!$this->getCreatedAt()) {
Есть

2022-09-29 09:56 UTC, StasPetrovSky1988 commented on src/Repository/ChatRepository.php
> +    public function remove(Chat $entity, bool $flush = false): void
Есть

2022-09-29 09:57 UTC, StasPetrovSky1988 commented on src/Entity/Chat.php
> +        if (!$user instanceof User) throw new \LogicException("User not found");
Есть

2022-09-29 10:08 UTC, StasPetrovSky1988 commented on src/DataFixtures/UserFixtures.php
> +        $message = Message::newMessage($userAdmin, $chat1, "This is first message by User Admin");
Есть

2022-09-29 11:12 UTC, kubk commented on src/Repository/UserRepository.php
> +        $this->getEntityManager()->flush();
Лучше просто вызывать entityManager->flush из контроллера
Репозитории ТОЛЬКО на чтение

2022-09-29 11:14 UTC, kubk requested changes

2022-09-29 11:14 UTC, kubk commented on src/Controller/ChatController.php
> +        $this->chatRepository->add($chat->addParticipant($participant));
Вот тут persist не нужен

$chat->addParticipant($participant)
$entityManager->flush()

Чтобы это работало нужно настроить cascade persist: https://www.doctrine-project.org/projects/doctrine-orm/en/2.13/reference/working-with-associations.html#transitive-persistence-cascade-operations

2022-09-29 16:09 UTC, kubk commented on src/Controller/ChatController.php
> +        private ManagerRegistry $registry,
Обычно передаём EntityManagerInterface

Тогда вместо  $this->registry->getManager()->flush() получаем  $this->entityManager()->flush()

2022-09-30 09:23 UTC, StasPetrovSky1988 commented on src/Controller/ChatController.php
> +        private ManagerRegistry $registry,
Есть

2022-09-30 09:24 UTC, StasPetrovSky1988 commented on src/Controller/ChatController.php
> +        $this->chatRepository->add($chat->addParticipant($participant));
Есть

2022-09-30 09:24 UTC, StasPetrovSky1988 commented on src/Repository/UserRepository.php
> +        $this->getEntityManager()->flush();
Есть

2022-09-30 10:24 UTC, merged